name: update_readme

on:
  push:
    branches:    
      - master
    paths:
      - 'words/*'

jobs:
  commit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - name: Update README.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python3 update_readme.py
        bash push.sh